site_name: Turdshovel
site_url: https://turdshovel.daddycocoaman.dev
site_description: "Go Ahead. Take a large dump."
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Oxygen Mono
  logo: images/turd-500.png
  favicon: images/turd-small.png

markdown_extensions:
  - meta
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mcohmi
